Repository pundarikaksha7/fashion-app, pull requests merged in 2025-03, with the labels that each got.

#10 Add .gitignore to ignore unnecessary files
  .gitignore
Labels: bug, codepeak 25, Easy

#20 Added profile image of the user who commented (#18)
  core/models.py
  templates/index.html
Labels: enhancement, codepeak 25, Easy

#16 Add feature of adding comments
  core/urls.py
  core/views.py
  templates/profile.html
Labels: bug, codepeak 25, Easy

#21 Fixed comment button on home screen which says 'POST' now
  core/__pycache__/__init__.cpython-312.pyc
  core/__pycache__/admin.cpython-312.pyc
  core/__pycache__/apps.cpython-312.pyc
  core/__pycache__/models.cpython-312.pyc
  core/__pycache__/urls.cpython-312.pyc
  core/__pycache__/views.cpython-312.pyc
  core/migrations/__pycache__/0001_initial.cpython-312.pyc
  core/migrations/__pycache__/0002_post.cpython-312.pyc
  core/migrations/__pycache__/0003_likepost.cpython-312.pyc
  core/migrations/__pycache__/0004_followerscount.cpython-312.pyc
  core/migrations/__pycache__/0005_alter_post_image.cpython-312.pyc
  core/migrations/__pycache__/0006_alter_post_image.cpython-312.pyc
  core/migrations/__pycache__/0007_alter_post_id_comment.cpython-312.pyc
  core/migrations/__pycache__/__init__.cpython-312.pyc
  db.sqlite3
  fashion_app/__pycache__/__init__.cpython-312.pyc
  fashion_app/__pycache__/settings.cpython-312.pyc
  fashion_app/__pycache__/urls.cpython-312.pyc
  fashion_app/__pycache__/wsgi.cpython-312.pyc
  media/profile_images/ANIRUDH-2.png
  media/profile_images/dark-vegeta-24fhvrz9n9m7ya6b.jpg
  static/css/style.css
  templates/index.html
Labels: bug, codepeak 25, Easy

#22 Feature/add issues and pr templates
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/PR_TEMPLATE.md
Labels: documentation, codepeak 25, Easy

#24 Fix: add_comment now correctly accepts post_id (#23)
  core/urls.py
  core/views.py
Labels: bug, codepeak 25, Medium

#29 Fix Like Feature and Comment Issue (#26)
  core/__pycache__/__init__.cpython-311.pyc
  core/__pycache__/__init__.cpython-312.pyc
  core/__pycache__/__init__.cpython-37.pyc
  core/__pycache__/admin.cpython-311.pyc
  core/__pycache__/admin.cpython-312.pyc
  core/__pycache__/admin.cpython-37.pyc
  core/__pycache__/apps.cpython-311.pyc
  core/__pycache__/apps.cpython-312.pyc
  core/__pycache__/apps.cpython-37.pyc
  core/__pycache__/models.cpython-311.pyc
  core/__pycache__/models.cpython-312.pyc
  core/__pycache__/models.cpython-37.pyc
  core/__pycache__/urls.cpython-311.pyc
  core/__pycache__/urls.cpython-312.pyc
  core/__pycache__/urls.cpython-37.pyc
  core/__pycache__/views.cpython-311.pyc
  core/__pycache__/views.cpython-312.pyc
  core/__pycache__/views.cpython-37.pyc
  core/migrations/__pycache__/0001_initial.cpython-311.pyc
  core/migrations/__pycache__/0001_initial.cpython-312.pyc
  core/migrations/__pycache__/0001_initial.cpython-37.pyc
  core/migrations/__pycache__/0002_post.cpython-311.pyc
  core/migrations/__pycache__/0002_post.cpython-312.pyc
  core/migrations/__pycache__/0002_post.cpython-37.pyc
  core/migrations/__pycache__/0003_likepost.cpython-311.pyc
  core/migrations/__pycache__/0003_likepost.cpython-312.pyc
  core/migrations/__pycache__/0003_likepost.cpython-37.pyc
  core/migrations/__pycache__/0004_followerscount.cpython-311.pyc
  core/migrations/__pycache__/0004_followerscount.cpython-312.pyc
  core/migrations/__pycache__/0004_followerscount.cpython-37.pyc
  core/migrations/__pycache__/0005_alter_post_image.cpython-311.pyc
  core/migrations/__pycache__/0005_alter_post_image.cpython-312.pyc
  core/migrations/__pycache__/0005_alter_post_image.cpython-37.pyc
  core/migrations/__pycache__/0006_alter_post_image.cpython-311.pyc
  core/migrations/__pycache__/0006_alter_post_image.cpython-312.pyc
  core/migrations/__pycache__/0006_alter_post_image.cpython-37.pyc
  core/migrations/__pycache__/0007_alter_post_id_comment.cpython-311.pyc
  core/migrations/__pycache__/0007_alter_post_id_comment.cpython-312.pyc
  core/migrations/__pycache__/__init__.cpython-311.pyc
  core/migrations/__pycache__/__init__.cpython-312.pyc
  core/migrations/__pycache__/__init__.cpython-37.pyc
  core/views.py
  db.sqlite3
  fashion_app/__pycache__/__init__.cpython-311.pyc
  fashion_app/__pycache__/__init__.cpython-312.pyc
  fashion_app/__pycache__/__init__.cpython-37.pyc
  fashion_app/__pycache__/settings.cpython-311.pyc
  fashion_app/__pycache__/settings.cpython-312.pyc
  fashion_app/__pycache__/settings.cpython-37.pyc
  fashion_app/__pycache__/urls.cpython-311.pyc
  fashion_app/__pycache__/urls.cpython-312.pyc
  fashion_app/__pycache__/urls.cpython-37.pyc
  fashion_app/__pycache__/wsgi.cpython-311.pyc
  fashion_app/__pycache__/wsgi.cpython-312.pyc
  fashion_app/__pycache__/wsgi.cpython-37.pyc
  templates/index.html
Labels: bug, codepeak 25, Medium
